# Data paths
BASE_DATA_PATH = 'joint_intent_slot_filling/data'
TRAINING_DATA_PATH = BASE_DATA_PATH + '/training_data.csv'
TEST_DATA_PATH = BASE_DATA_PATH + '/test_data.csv'
INTENT_CLASSES_PATH = BASE_DATA_PATH + '/intent_classes.csv'
SLOTS_CLASSES_PATH = BASE_DATA_PATH + '/slots_classes.csv'

# Auxiliary files paths
AUXILIARY_DIRECTORY = 'joint_intent_slot_filling/auxiliaries'
BERT_VOCAB_FILE_PATH = AUXILIARY_DIRECTORY + '/vocab.txt'

# Trained model constants
TRAINED_MODEL_DIRECTORY = 'joint_intent_slot_filling/trained_model'
TRAINED_MODEL_ASSETS_DIRECTORY = TRAINED_MODEL_DIRECTORY + '/assets'
TRAINED_MODEL_VARIABLES_DIRECTORY = TRAINED_MODEL_DIRECTORY + '/variables'
TRAINED_MODEL_SAVED_MODEL_FILE = TRAINED_MODEL_DIRECTORY + '/saved_model.pb'
TRAINED_MODEL_SAVED_MODEL_FILE_DRIVE_ID = '1ksY4BFVSyNHvEYBIOdN_zLUpFoDgueE0'
TRAINED_MODEL_VOCAB_ASSETS_FILE = TRAINED_MODEL_ASSETS_DIRECTORY + '/vocab.txt'
TRAINED_MODEL_VOCAB_ASSETS_FILE_DRIVE_ID = '12bry3fY25eZew7K4b8XKESxjP1CQ8gfS'
TRAINED_MODEL_CHECKPOINT_VARIABLE_FILE = TRAINED_MODEL_VARIABLES_DIRECTORY + '/variables.data-00000-of-00001'
TRAINED_MODEL_CHECKPOINT_VARIABLE_FILE_DRIVE_ID = '1oLDXyOlwxCCLEl_U8NEH4qaB70hZepk0'
TRAINED_MODEL_VARIABLE_INDEX_FILE = TRAINED_MODEL_VARIABLES_DIRECTORY + '/variables.index'
TRAINED_MODEL_VARIABLE_INDEX_FILE_DRIVE_ID = '1l_9B8yHBUwQT0qEXYcAviIYYXmUhuCEs'
TRAINED_MODEL_MAX_SEQUENCE_FILE = TRAINED_MODEL_DIRECTORY + '/max_sequence_value.txt'
TRAINED_MODEL_MAX_SEQUENCE_FILE_DRIVE_ID = '1u1_7HvuCtRDHzyGRnEspneplYbSEXC4x'

# Encoders
SLOTS_LABEL_ENCODER_FILE = TRAINED_MODEL_DIRECTORY + '/slots_encoder.pkl'
SLOTS_LABEL_ENCODER_FILE_DRIVE_ID = '1YwUfd5lP04UMZURLy6liAfhaMP4TVHEM'
INTENT_LABEL_ENCODER_FILE = TRAINED_MODEL_DIRECTORY + '/intent_encoder.pkl'
INTENT_LABEL_ENCODER_FILE_DRIVE_ID = '1bs4oRqw5siMqN_ZxZ5HvbhOoAYXY0YKg'

# Model Metrics
MODEL_METRICS_DIRECTORY = 'joint_intent_slot_filling/metrics'
MODEL_METRICS_REPORT_FILE = MODEL_METRICS_DIRECTORY + '/metrics_report.txt'
MODEL_CONFUSION_MATRIX_FILE = MODEL_METRICS_DIRECTORY + '/confusion_matrix.pdf'

# Old data paths
OLD_TRAINING_DATA_PATH = BASE_DATA_PATH + '/training_data_old.csv'
OLD_TEST_DATA_PATH = BASE_DATA_PATH + '/test_data_old.csv'
OLD_TRAINED_MODEL_DIRECTORY = 'joint_intent_slot_filling/trained_model_old'
OLD_TRAINED_MODEL_MAX_SEQUENCE_FILE = OLD_TRAINED_MODEL_DIRECTORY + '/max_sequence_value.txt'
OLD_SLOTS_LABEL_ENCODER_FILE = OLD_TRAINED_MODEL_DIRECTORY + '/slots_encoder.pkl'
OLD_INTENT_LABEL_ENCODER_FILE = OLD_TRAINED_MODEL_DIRECTORY + '/intent_encoder.pkl'
OLD_MODEL_METRICS_REPORT_FILE = MODEL_METRICS_DIRECTORY + '/metrics_report_old.txt'
OLD_MODEL_CONFUSION_MATRIX_FILE = MODEL_METRICS_DIRECTORY + '/confusion_matrix_old.pdf'

# Location Extractor constants
LOCATION_EXTRACTOR_TEST_DATA_PATH = 'data/location_extractor_test_data.csv'
LOCATION_EXTRACTOR_TEST_RESULT_METRICS = 'metrics/location_extractor_metrics_report.txt'

# Inference logs constants
INFERENCE_LOGS_FILE_LOCATION = 'joint_intent_slot_filling/logs/inference_logs.txt'
